name: Execute tests

on:
  push:
    branches:
      - dev
      - Recipes-home

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: Install docker compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: latest
          legacy: true

      - name: "Create ssh fake key"
        run: |
          mkdir ~/.ssh
          echo "" > ~/.ssh/id_ed25519

      - name: "Build containers"
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./.docker/build/docker-compose.yml"
          services: |
            nginx
            php
          compose-flags: |
            --env-file ./.docker/build/env/.env
        env:
          USER_ID: 1001
          GROUP_ID: 1001

      - name: Setting up project for development
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            exec -u 0 php bash -c "whoami \
                                   && ls -la ./home/runner/work \
                                   && cd ./home/runner/work \
                                   && pwd \
                                   && make setup-test"
            # exec -u 0 php bash -c "cd /home/developer/Recipes && pwd && ls -la && ls -la /home/developer/Recipes && make setup-test"

      - name: Containers up
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            ps

      - name: Execute tests
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            exec -u 0 php bash -c "cd /home/developer/Recipes && bin/phpunit"