name: Execute tests

on:
  push:
    branches:
      - dev
      - Recipes-home
      - main

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: Install docker compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: latest
          legacy: true

      - name: Pull the latest images to build
        run: docker-compose pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: "Create ssh fake key"
        run: |
          mkdir ~/.ssh
          echo "" > ~/.ssh/id_ed25519

      - name: "Build containers"
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./.docker/build/docker-compose.yml"
          services: |
            nginx
            php
            mysql
            composer
          compose-flags: |
            --env-file ./.docker/build/env/.env
        env:
          USER_ID: 1001
          GROUP_ID: 1001

      - name: Setting up project for development
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            exec -u 1001 php bash -c "cd ./home/runner/work/Recipes/Recipes \
                                      && make setup-test"

      - name: Containers up
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            ps

      - name: Execute tests
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            exec -u 1001 php bash -c "cd ./home/runner/work/Recipes/Recipes \
                                      && bin/phpunit"

