name: Execute tests

on:
  push:
    branches:
      - dev
      - Recipes-home

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - name: Build the backend image with cache
        uses: docker/build-push-action@v6
        with:
          load: true
          # context: backend
          # file: backend/Dockerfile.dev
          cache-from: type=gha,scope=$GITHUB_REF_NAME-backend-dev
          cache-to: type=gha,scope=$GITHUB_REF_NAME-backend-dev,mode=max

      - name: Setting the containers up
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            up -d

