name: Execute tests

on:
  push:
    branches:
      - dev
      - Recipes-home

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3


      - name: Setting the containers up
        run: |
          docker-compose \
            --file ./.docker/build/docker-compose.yml \
            --env-file ./.docker/build/env/.env \
            up -d

